### ISSUE TITLE
inactive button 

### ISSUE THREAD

**Issue by issuesfixer** [AigangNetwork/aigangnetwork.github.io#1]
![screen shot 2018-05-16 at 3 29 25 pm](https://user-images.githubusercontent.com/39336882/40116957-160e8a72-591e-11e8-8b63-3e25aee952b5.png)

**Comment by dyoann** [comment]
You need to login to use this data I believe, maybe a tooltip with "please login, blabla" 
would be helpful ?

**Comment by DomantasP** [comment]
Moved to https://github.com/AigangNetwork/aigang-platform-web/issues/47
